# ---------------------------------------------------------------------------- #
#' Modify how `checkmate` handles output of its checks
#'
#' This is a closure intended for running a `checkmate` check and always
#' returning TRUE or FALSE so that it can be used in conditional statements. If
#' the check fails, it will optionally emit the error message returned by
#' checkmate.
#' @param fun A `checkmate` check, for example `checkmate::check_integer`.
#'
#' @return A function which runs the specified  `checkmate` check functions. See
#'   'Returned Function' for details.
#'
#' @section Returned Function: The returned function runs a `checkmate` check.
#'
#' **Arguments**\cr
#' \describe{
#'    \item{...}{Arguments passed on to the specified `checkmate`
#'      function.}
#'    \item{quiet}{A logical which is TRUE if a failed check should not emit its
#'      error message; FALSE if it should.\cr Default: TRUE}
#' }
#' **Value**\cr
#' A logical which is TRUE if the check succeeded and FALSE if not. The message
#'   generated by a failed check is set as an attribute of the return value.
#'
#' @seealso [cli::cli_abort()]
#' @examples
#' # Note: chk_choice is created as follows:
#' # chk_choice <- checkmate_chk(checkmate::check_choice)
#' valid_choices <- c("pineapple", "blueberry", "peach")
#'
#' # The following check succeeds:
#' chk_choice("peach", valid_choices)
#'
#' # The following check fails and *does not* emit the error message:
#' chk_choice("avocado", valid_choices, quiet = TRUE)
#'
#' # The following check fails and *does* emit the error message:
#' chk_choice("avocado", valid_choices)
#'
#' # Use this check in a conditional statement:
#' if (!chk_choice("avocado", valid_choices)) {
#'   # Do something as a result of the failure ...
#'   warning("Check failed.")
#' }
#'
#' \dontrun{
#' # An example of using this check with `cli::cli_abort`:
#' if (!(res <- chk_choice("tractor", valid_choices))) {
#'   cli::cli_abort("{cli::cli_verbatim(attr(res, 'err_msg'))}")
#' }
#' }
checkmate_chk <- function(fun) {

  # ------------------------------------ #
  function(..., quiet = TRUE) {

    result <- fun(...)

    # The way checkmate returns results of a check is that if the check passes,
    # it returns TRUE but if it fails, it returns the error message. This means
    # it the check cannot be used in a conditional statement.
    # Hence:
    # If there was an error, capture the message, set the result to FALSE and
    # set the error message as an attribute of the result. In this way, the
    # return value is always a logical (rather than a logical if the check
    # succeeds but a character string if the check fails).

    if (!is.logical(result) || isFALSE(result)) {
      err_msg <- result
      cli_msg <- cli::cli_fmt({
        cli::cli_bullets(c("!" = "{err_msg}"))
      })
      if (!quiet) cli::cat_line(cli_msg, sep = "\n")
      result <- FALSE
      attr(result, "err_msg") <- err_msg
    }

    invisible(result)
  }
}

# ------------------------------------ #
#' @keywords internal
#' @noRd
chk_atomic_vector <- checkmate_chk(checkmate::check_atomic_vector)

#' Modify how `checkmate` handles output of `checkmate::check_choice`
#'
#' @param ... Arguments passed on to the specified `checkmate` function.
#' @param quiet A logical which is TRUE if a failed check should not emit its
#'   error message; FALSE if it should. Default: TRUE
#'
#' @return A logical which is TRUE if the check succeeded and FALSE if not. The
#'   message generated by a failed check is set as an attribute of the return
#'   value.
#' @export
chk_choice <- checkmate_chk(checkmate::check_choice)

#' @keywords internal
#' @noRd
chk_integerish <- checkmate_chk(checkmate::check_integerish)

#' @keywords internal
#' @noRd
chk_null <- checkmate_chk(checkmate::check_null)

#' @keywords internal
#' @noRd
chk_numeric <- checkmate_chk(checkmate::check_numeric)

#' @keywords internal
#' @noRd
chk_matrix <- checkmate_chk(checkmate::check_matrix)

#' @keywords internal
#' @noRd
chk_scalar_na <- checkmate_chk(checkmate::check_scalar_na)

# ---------------------------------------------------------------------------- #
#' Format an argument for printing, retaining only a given number of lines to
#' display
#'
#' @param arg The argument to print
#' @param max_lines The maximum number of lines of output to show for the
#'   printed argument. This would include, for example, a line for the column
#'   numbers/names of a matrix (e.g. "\[,1]  \[,2]").
#' @param bullet_theme A character for the `cli::cli_bullets` theme.
#'
#' @return A named character vector which is the result of printing the
#'   argument, up to a maximum of `max_lines`, named by the value of
#'   `bullet_theme`.
#'
#' @seealso [cli::cli_verbatim()]
#' @export
#' @examples
#' x <- matrix(c(6.62,      4.9,     1.94,
#'               4.9,      -3.524,  10.5,
#'               100.94, -678.5,   -20.95), 3, 3)
#' cli::cli_verbatim(glimpse_arg(x))
#' # Or, e.g.:
#' cli::cli_inform(cli::cat_line(glimpse_arg(x)))
glimpse_arg <- function(arg, max_lines = 3, bullet_theme = " ") {

  output <- capture.output(print(arg))

  # Only retain up to max_lines lines
  n_lines_info <- ""
  if (length(output) > max_lines) {
    n_more <- length(output) - max_lines # nolint: object_usage_linter
    n_lines_info <- cli::pluralize("and {n_more} more line{?s} ...")
  }

  output <- output[seq_len(min(length(output), max_lines))]

  if (nchar(n_lines_info) > 0) output <- c(output, n_lines_info)

  # Use bullet_theme to set the cli::cli_bullets theme (default is an indent)
  setNames(output, rep(bullet_theme, length(output)))
}

# ---------------------------------------------------------------------------- #
