# ---------------------------------------------------------------------------- #
#' Wrap a `checkmate` check to handle its output differently
#'
#' This is a closure intended for running a `checkmate` check and always
#' returning TRUE or FALSE so that it can be used in conditional statements. If
#' the check fails, it will optionally emit the error message returned by
#' checkmate.
#' @param fun A `checkmate` check, for example `checkmate::check_integer`.
#'
#' @return A function which runs the specified  `checkmate` check functions. See
#'   'Returned Function' for details.
#'
#' @section Returned Function: The returned function runs a `checkmate` check.
#'
#' **Arguments**\cr
#' \describe{
#'    \item{...}{Arguments passed on to the specified `checkmate`
#'      function.}
#'    \item{quiet}{A logical which is TRUE if a failed check should not emit its
#'      error message; FALSE if it should.\cr Default: TRUE}
#' }
#' **Value**\cr
#' A logical which is TRUE if the check succeeded and FALSE if not. The message
#'   generated by a failed check is set as an attribute of the return value.
#'
#' @seealso [cli::cli_abort()]
#'
#' @examples
#' # Note: chk_choice is created as follows:
#' # chk_choice <- checkmate_chk(checkmate::check_choice)
#' valid_choices <- c("pineapple", "blueberry", "peach")
#'
#' # The following check succeeds:
#' chk_choice("peach", valid_choices)
#'
#' # The following check fails and *does not* emit the error message:
#' chk_choice("avocado", valid_choices, quiet = TRUE)
#'
#' # The following check fails and *does* emit the error message:
#' chk_choice("avocado", valid_choices)
#'
#' # Use this check in a conditional statement:
#' if (!chk_choice("pineapple", valid_choices)) {
#'   # Do something as a result of the failure ...
#'   warning("Value 'pineapple' is not a valid option.")
#' }
#'
#' \dontrun{
#' # An example of using this check with `cli::cli_abort`:
#' res <- chk_choice("tractor", valid_choices)
#' if (!res) {
#'   cli::cli_abort("{cli::cli_verbatim(attr(res, 'err_msg'))}")
#' }
#' }
#'
checkmate_chk <- function(fun) {

  # ------------------------------------ #
  function(..., quiet = TRUE) {

    result <- fun(...)

    # The way checkmate returns results of a check is that if the check passes,
    # it returns TRUE but if it fails, it returns the error message. This means
    # it the check cannot be used in a conditional statement.
    # Hence:
    # If there was an error, capture the message, set the result to FALSE and
    # set the error message as an attribute of the result. In this way, the
    # return value is always a logical (rather than a logical if the check
    # succeeds but a character string if the check fails).

    if (!is.logical(result) || isFALSE(result)) {
      err_msg <- result
      cli_msg <- cli::cli_fmt({
        cli::cli_bullets(c("!" = "{err_msg}"))
      })
      if (!quiet) cli::cat_line(cli_msg, sep = "\n")
      result <- FALSE
      attr(result, "err_msg") <- err_msg
    }

    invisible(result)
  }
}

# ------------------------------------ #
#' @keywords internal
#' @noRd
chk_atomic_vector <- checkmate_chk(checkmate::check_atomic_vector)

#' Wrap `checkmate::check_choice` to handle its output differently
#'
#' This wrapper always returns TRUE or FALSE so that it can be used in
#' conditional statements. If the check fails, it will optionally emit the error
#' message returned by checkmate.
#'
#' @param ... Arguments passed on to the specified `checkmate` function.
#' @param quiet A logical which is TRUE if a failed check should not emit its
#'   error message; FALSE if it should. Default: TRUE
#'
#' @return A logical which is TRUE if the check succeeded and FALSE if not. The
#'   message generated by a failed check is set as an attribute of the return
#'   value.
#' @export
chk_choice <- checkmate_chk(checkmate::check_choice)

#' @keywords internal
#' @noRd
chk_class <- checkmate_chk(checkmate::check_class)

#' @keywords internal
#' @noRd
chk_data_frame <- checkmate_chk(checkmate::check_data_frame)

#' @keywords internal
#' @noRd
chk_function <- checkmate_chk(checkmate::check_function)

#' @keywords internal
#' @noRd
chk_integerish <- checkmate_chk(checkmate::check_integerish)

#' @keywords internal
#' @noRd
chk_list <- checkmate_chk(checkmate::check_list)

#' @keywords internal
#' @noRd
chk_logical <- checkmate_chk(checkmate::check_logical)

#' @keywords internal
#' @noRd
chk_null <- checkmate_chk(checkmate::check_null)

#' @keywords internal
#' @noRd
chk_numeric <- checkmate_chk(checkmate::check_numeric)

#' @keywords internal
#' @noRd
chk_matrix <- checkmate_chk(checkmate::check_matrix)

#' @keywords internal
#' @noRd
chk_scalar_na <- checkmate_chk(checkmate::check_scalar_na)

# ---------------------------------------------------------------------------- #
